version: '2.1'

services:
  demo-mysql:
    image: mysql:5.6
    container_name: demo-mysql
    healthcheck:
     test: "exit 0"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
  task-manager-backend:
    image: task-manager-backend
    container_name: task-manager-backend
    depends_on:
     demo-mysql:
      condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=demo-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306

